version: '3'
services:
  web:           #nome do serviço  
    build: 
      context: . #definir a origem dos arquivos a serem executados
      dockerfile: Dockerfile.dev  #definir o nome do Dockerfile caso NAO seja o default
    ports:
      - "80:8080" #fora do container : dentro do container
    environment:
      - CHOKIDAR_USEPOLLING=true  #atualizar sempre
    volumes:
      - /app/node_modules  #nao mapear
      - .:/app   #diretorio wd fora do container : para pasta DENTRO do container
  tests:
    build: 
      context: . #definir a origem dos arquivos a serem executados
      dockerfile: Dockerfile.dev  #definir o nome do Dockerfile caso NAO seja o default
    environment:
      - CHOKIDAR_USEPOLLING=true  #atualizar sempre
    volumes:
      - /app/node_modules  #nao mapear
      - .:/app   #diretorio wd fora do container : para pasta DENTRO do container
    command: #["npm", "run", "test"]
      - npm
      - run
      - test
      
